# Generated by Django 5.0.4 on 2024-05-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('subiect', models.CharField(max_length=255)),
                ('mesaj', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('numar_telefon', models.CharField(max_length=11)),
            ],
        ),
    ]
