# Generated by Django 5.0.4 on 2024-04-27 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('bleu', 'Bleu'), ('roz', 'Roz'), ('alb', 'Alb'), ('lila', 'Lila'), ('verde', 'Verde')], max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
