# Generated by Django 5.0.4 on 2024-05-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('bleu', 'Bleu'), ('roz', 'Roz'), ('alb', 'Alb'), ('lila', 'Lila'), ('verde', 'Verde'), ('mov', 'Mov'), ('galben', 'Galben')], max_length=10),
        ),
    ]
